/**
 * Created by feichongzheng on 17/9/25.
 */
export const NOT_NEED_FIND_UUMS_RESOURCE_AUTH = 'UUMS/NOTNEEDFINDRESOURCEAUTH';
export const FIND_UUMS_RESOURCE_AUTH = 'UUMS/FINDRESOURCEAUTH';
export const FIND_UUMS_RESOURCE_AUTH_FETCH = 'UUMS/FINDRESOURCEAUTHFETCH';
export const FIND_UUMS_RESOURCE_AUTH_SUCCESS = 'UUMS/FINDRESOURCEAUTHSUCCESS';
export const FIND_UUMS_RESOURCE_AUTH_ERROR = 'UUMS/FINDRESOURCEAUTHERROR';
